GeeksForLess/Models/DirectoryEllement.cs
using System.ComponentModel.DataAnnotations;

namespace GeeksForLess.Models
{
    public class DirectoryEllement
    {
        public string? Name { get; set; }
        public string? RootPath { get; set; } = "D:";
    }
}

GeeksForLess/Models/Folder.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace GeeksForLess.Models
{
    public class Folder
    {
        [Key]
        [JsonIgnore]
        public int Id { get; set; }
        public int FolderKey { get; set; }
        public string Name { get; set; }
        public string? ChildFoldersKeys { get; set; }
        public bool IsSelected { get; set; } = false;
    }
}

GeeksForLess/Controllers/FolderController.cs
using GeeksForLess.Data;
using GeeksForLess.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using static NuGet.Packaging.PackagingConstants;

namespace GeeksForLess.Controllers
{
    public class FolderController : Controller
    {
        private readonly ApplicationDbContext _db;

        public FolderController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(Folder newParentFolder = null)
        {
            if (newParentFolder.Id != 0)
            {
                var oldParentFolder = _db.Folder.Where(x => x.IsSelected == true).First();
                newParentFolder = _db.Folder.Where(x => x.Id == newParentFolder.Id).First();

                oldParentFolder.IsSelected = false;
                newParentFolder.IsSelected = true;

                _db.Folder.Update(newParentFolder);
                _db.Folder.Update(oldParentFolder);

                _db.SaveChanges();
            }

            IEnumerable<Folder> folders = _db.Folder;

            return View(folders.OrderByDescending(x => x.IsSelected));
        }

        public IActionResult SaveDbToJson()
        {
            return View(new DirectoryEllement());
        }

        [HttpPost]
        public IActionResult SaveDbToJson(DirectoryEllement file)
        {
            if(file.Name == null)
            {
                file.Name = $"{Guid.NewGuid()}.json";
            }
            
            IEnumerable<Folder> folders = _db.Folder;

            var json = JsonConvert.SerializeObject(folders);

            try
            {
                string rootPath = string.Empty;

                if (file.RootPath != null)
                {
                    rootPath = file.RootPath.EndsWith("\\") ? file.RootPath : $"{file.RootPath}\\";
                }

                using StreamWriter creatingFile = new(rootPath + file.Name);

                creatingFile.Write(json);

                return RedirectToAction("Index");
            }
            catch
            {
                return NotFound();
            }

        }

        public IActionResult GetDbFromJson()
        {
            return View(new DirectoryEllement());
        }

        [HttpPost]
        public IActionResult GetDbFromJson(DirectoryEllement file)
        {
            if (file.Name == null)
            {
                return NotFound();
            }
            try
            {
                string rootPath = string.Empty;

                if (file.RootPath != null)
                {
                    rootPath = file.RootPath.EndsWith("\\") ? file.RootPath : $"{file.RootPath}\\";
                }

                var data = System.IO.File.ReadAllText(rootPath + file.Name);

                var folders = JsonConvert.DeserializeObject<IEnumerable<Folder>>(data);

                ChangeDataInDb(folders);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(new DirectoryEllement()); 
            }
        }

        public IActionResult GetDbFromSystemDir()
        {
            return View(new DirectoryEllement());
        }

        [HttpPost]
        public IActionResult GetDbFromSystemDir(Models.DirectoryEllement file)
        {
            var rootPath = file.RootPath.EndsWith("\\") ? file.RootPath : $"{file.RootPath}\\";
            var currentFolderName = file.Name;

            List<Folder> folders = new();

            var currentRootPath = $"{rootPath}\\{currentFolderName}";

            if (Directory.Exists(rootPath))
            {
                folders = AddChildFolders(folders, -1, new[] { currentRootPath }, rootPath);

                ChangeDataInDb(folders);

                return RedirectToAction("Index");
            }
            else
            {
                return NotFound();
            }

        }

        private void ChangeDataInDb(IEnumerable<Folder> folders)
        {
            if (_db.Folder.Count() != 0)
            {
                _db.Folder.RemoveRange(_db.Folder);
            }

            _db.Folder.AddRange(folders);

            _db.SaveChanges();
        }

        private List<Folder> AddChildFolders(List<Folder> folders, int rootFolderKey, string[] childFolderPaths, string rootPath)
        {
            foreach(var currentRootPath in childFolderPaths)
            {
                if (Directory.Exists(currentRootPath))
                {
                    int currentKey = folders.Count();

                    folders.Add(new Folder
                    {
                        Name = currentRootPath.Replace($"{rootPath}\\", string.Empty),
                        FolderKey = currentKey,
                    });

                    if(rootFolderKey != -1)
                    {
                        folders.Single(x => x.FolderKey == rootFolderKey).ChildFoldersKeys += $" {currentKey}";
                        folders.Single(x => x.FolderKey == rootFolderKey).IsSelected = true;
                    }

                    string[] currentChildFolderPaths = Directory.GetDirectories(currentRootPath, "*", SearchOption.TopDirectoryOnly);

                    if (childFolderPaths.Length != 0)
                    {
                        folders = AddChildFolders(folders, currentKey, currentChildFolderPaths, currentRootPath);
                    }
                }
            }

            return folders;
        }
    }
}

GeeksForLess/Controllers/HomeController.cs
using GeeksForLess.Data;
using GeeksForLess.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GeeksForLess.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public HomeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            if(_db.Folder.Count() != 0)
            {
                var activeFolders = _db.Folder.Where(x => x.IsSelected == true);

                foreach (var folder in activeFolders)
                {
                    folder.IsSelected = false;
                    _db.Folder.Update(folder);
                }

                var newParentFolder = _db.Folder.OrderBy(x => x.FolderKey).First();

                newParentFolder.IsSelected = true;

                _db.Folder.Update(newParentFolder);

                _db.SaveChanges();

                return View(newParentFolder);
            }
            return View();

        }

    }
}

GeeksForLess/Views/Folder/GetDbFromJson.cshtml
@model GeeksForLess.Models.DirectoryEllement


<form method="post">
    <div class="container">
        <div class="row" style="margin-top:25px">
            <div class="form-group row">
                <div class="col-4">
                    <label>Root path</label>
                    <input asp-for="RootPath" class="form-control" />
                    <span asp-validation-for="RootPath" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label>File name</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-4">

                    <div style="margin-top:10px" class="col">
                        <input type="submit" class="btn btn-info w-100" value="Continue" />
                    </div>
                    <div style="margin-top:10px" class="col">
                        <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

GeeksForLess/Views/Folder/GetDbFromSystemDir.cshtml
@model GeeksForLess.Models.DirectoryEllement


<form method="post">
    <div class="container">
        <div class="row" style="margin-top:25px">
            <div class="form-group row">
                <div class="col-4">
                    <label>Root path</label>
                    <input asp-for="RootPath" class="form-control" />
                    <span asp-validation-for="RootPath" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label>Folder name</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">

                    <div style="margin-top:10px" class="col">
                        <input type="submit" class="btn btn-info w-100" value="Save" />
                    </div>
                    <div style="margin-top:10px" class="col">
                        <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

GeeksForLess/Views/Folder/Index.cshtml
@model IEnumerable<GeeksForLess.Models.Folder>

<div class="container">

    <div class="header">
        <a asp-controller="Home" asp-action="Index">Home</a>
        <a> | </a>
        <a asp-controller="Folder" asp-action="SaveDbToJson">Save</a>
    </div>

    @if (Model.Count() > 0)
    {
        @if (Model.First().IsSelected)
        {
            <div style="margin-top:25px">
                <p style="font-weight:600">"Folder" - @Model.First().Name</p>

                @foreach (var obj in Model)
                {
                    @if (Model.First().ChildFoldersKeys != null)
                    {
                        @if (Model.First().ChildFoldersKeys.Contains(obj.FolderKey.ToString()))
                        {
                            <a asp-controller="Folder" asp-route-Id="@obj.Id" asp-action="Index">
                                <p>@obj.Name</p>
                            </a>
                        }
                    }
                }

            </div>
        }
    }

</div>

GeeksForLess/Views/Folder/SaveDbToJson.cshtml
@model GeeksForLess.Models.File


<form method="post">
    <div class="container">
        <div class="row" style="margin-top:25px">
            <div class="form-group row">
                <div class="col-4">
                    <label style="position:center">File name</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

            </div>


            <div class="form-group row">
                <div class="col-4">

                    <div style="margin-top:10px" class="col">
                        <input type="submit" class="btn btn-info w-100" value="Save" />
                    </div>
                    <div style="margin-top:10px" class="col">
                        <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

GeeksForLess/Views/Home/Index.cshtml
@model GeeksForLess.Models.Folder

<div class="container">

    <div class="header">
        <a asp-controller="Folder" asp-action="GetDbFromJson">Get data from file</a>
        <a> | </a>
        <a asp-controller="Folder" asp-action="GetDbFromSystemDir">Get data from system</a>
    </div>

    @if(Model != null && Model.Id != 0)
    {
        <div style="margin-top:25px">
            <a style="font-weight:600">"Check Folder" - </a>
            <a asp-controller="Folder" asp-action="Index" class="text-primary">@Model.Name</a>
        </div>
    }
    
</div>

GeeksForLess/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>